<?php

namespace App\Http\Controllers\Seo;

use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use SplFileInfo;
use Symfony\Component\Finder\Finder;

/**
 * Serves /sitemap.xml.
 *
 * PullLens has exactly two public surfaces - the landing page and the pre-built
 * user guide - so the sitemap is generated by listing the guide's HTML files
 * rather than maintained by hand. A page added to the guide appears in the
 * sitemap on the next deploy without anybody remembering to add it.
 *
 * `lastmod` is each file's own modification time. That is honest: a crawler is
 * told the guide changed when the guide actually changed, and not on every
 * deploy, which is what a build timestamp would claim.
 *
 * Withdrawn entirely when HOMEPAGE_LOGIN is on, for the same reason the guide is
 * (see EnsurePublicPagesAreEnabled): an internal instance should not hand a
 * crawler a map of itself.
 */
class SitemapController extends Controller
{
    /** The guide's landing file, which deserves a higher priority than its pages. */
    private const GUIDE_INDEX = 'guide/index.html';

    /**
     * Render the sitemap.
     */
    public function __invoke(): Response
    {
        $base = rtrim((string) config('app.url'), '/');

        $urls = [
            $this->url($base.'/', $this->appLastModified(), 'weekly', '1.0'),
        ];

        foreach ($this->guidePages() as $relative => $modified) {
            $urls[] = $this->url(
                $base.'/docs/'.$relative,
                $modified,
                'monthly',
                $relative === self::GUIDE_INDEX ? '0.8' : '0.6',
            );
        }

        $xml = '<?xml version="1.0" encoding="UTF-8"?>'."\n"
            .'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."\n"
            .implode('', $urls)
            .'</urlset>'."\n";

        return response($xml, 200, [
            'Content-Type' => 'application/xml; charset=utf-8',
            'Cache-Control' => 'public, max-age=3600',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }

    /**
     * One <url> entry.
     */
    private function url(string $location, int $modified, string $frequency, string $priority): string
    {
        return '  <url>'."\n"
            .'    <loc>'.htmlspecialchars($location, ENT_XML1).'</loc>'."\n"
            .'    <lastmod>'.gmdate('Y-m-d', $modified).'</lastmod>'."\n"
            .'    <changefreq>'.$frequency.'</changefreq>'."\n"
            .'    <priority>'.$priority.'</priority>'."\n"
            .'  </url>'."\n";
    }

    /**
     * Every HTML page in the guide, keyed by its path relative to `docs/`.
     *
     * @return array<string, int>
     */
    private function guidePages(): array
    {
        $root = base_path('docs');

        if (! is_dir($root)) {
            return [];
        }

        $pages = [];

        foreach (Finder::create()->files()->in($root)->name('*.html')->sortByName() as $file) {
            /** @var SplFileInfo $file */
            if ($this->isRedirect($file)) {
                continue;
            }

            $pages[str_replace(DIRECTORY_SEPARATOR, '/', $file->getRelativePathname())] = (int) $file->getMTime();
        }

        return $pages;
    }

    /**
     * Whether a page only forwards somewhere else.
     *
     * `docs/index.html` is a meta-refresh onto the guide, and the guide may grow
     * more of them. Listing a redirect in a sitemap asks a crawler to fetch a page
     * whose only content is the address of another page already in the list.
     */
    private function isRedirect(SplFileInfo $file): bool
    {
        // The refresh is in the head; no page puts one thousands of bytes down.
        $head = (string) file_get_contents($file->getPathname(), false, null, 0, 2048);

        return str_contains($head, 'http-equiv="refresh"')
            || str_contains($head, "http-equiv='refresh'");
    }

    /**
     * When the landing page last changed.
     *
     * The page is a compiled React component, so its source file is the closest
     * thing to a publication date the application has; falling back to today
     * keeps the sitemap valid on an installation that deployed without sources.
     */
    private function appLastModified(): int
    {
        $source = base_path('resources/js/pages/welcome.tsx');

        return is_file($source) ? (int) filemtime($source) : time();
    }
}
